from django.urls import path, include # Ensure 'include' is imported
from rest_framework.routers import DefaultRouter # Import the router
from .views import (
    
    # Import the ViewSets
    PostViewSet,
    CategoryViewSet, 
    CommentListCreateView,
    CommentRetrieveDestroyView,
)

# 1. Create a router instance
# DefaultRouter provides the standard routes plus a default API root view
router = DefaultRouter()

# 2. Register the ViewSets with the router
# router.register(prefix, viewset, basename)
# 'prefix' is the URL prefix for this ViewSet (e.g., 'posts')
# 'viewset' is the ViewSet class itself
# 'basename' is used to create the URL names (e.g., 'post-list', 'post-detail').
# It's required if the ViewSet doesn't have a 'queryset' attribute or if DRF can't infer the model name.
router.register(r'posts', PostViewSet, basename='post')
router.register(r'categories', CategoryViewSet, basename='category')

# 3. Define urlpatterns
urlpatterns = [
    # Include the URLs automatically generated by the router
    # This will create URLs like:
    # /api/posts/
    # /api/posts/{pk}/
    # /api/posts/{pk}/like/
    # /api/posts/{pk}/dislike/
    # /api/categories/
    # /api/categories/{pk}/
    path('', include(router.urls)),

    
    
    path('posts/<int:post_pk>/comments/', CommentListCreateView.as_view(), name='comment-list-create'),
    path('posts/<int:post_pk>/comments/<int:comment_pk>/', CommentRetrieveDestroyView.as_view(), name='comment-detail'),
]

